BVSneaker/Models/EF/Advertisement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BVSneaker.Models.EF
{
    [Table("tb_Advertisement")]
    public class Advertisement : CommonAbstract
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Adv_Id { get; set; }

        [Required(ErrorMessage = "Tên không được để trống")]
        [StringLength(150, ErrorMessage = "Không được vượt quá 150 kí tự")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Image { get; set; }
        public string Alias { get; set; }
    }
}

BVSneaker/Areas/Admin/Controllers/AdvertisementController.cs
using BVSneaker.Models.EF;
using BVSneaker.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BVSneaker.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,Employee")]
    public class AdvertisementController : Controller
    {
        private ApplicationDbContext _dbConnect = new ApplicationDbContext();
        // GET: Admin/Advertisement
        public ActionResult Index(string Searchtext, int? page)
        {
            var pageSize = 6;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<Advertisement> items = _dbConnect.Advertisements.OrderByDescending(x => x.Adv_Id);
            if (!string.IsNullOrEmpty(Searchtext))
            {
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Advertisement model)
        {
            if (ModelState.IsValid)
            {
                if (model.Alias == null)
                {
                    model.Alias = BVSneaker.Models.Common.Filter.FilterChar(model.Title);
                }
                model.CreateDate = DateTime.Now;
                model.ModDate = DateTime.Now;
                _dbConnect.Advertisements.Add(model);
                _dbConnect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var item = _dbConnect.Advertisements.Find(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Advertisement model)
        {
            if (ModelState.IsValid)
            {
                _dbConnect.Advertisements.Attach(model);
                model.ModDate = DateTime.Now;
                if (model.Alias == null)
                {
                    model.Alias = BVSneaker.Models.Common.Filter.FilterChar(model.Title);
                }
                _dbConnect.Entry(model).Property(x => x.Title).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.Description).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.Alias).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.Image).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.ModBy).IsModified = true;
                _dbConnect.Entry(model).Property(x => x.ModDate).IsModified = true;
                _dbConnect.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var item = _dbConnect.Advertisements.Find(id);
            if (item != null)
            {
                _dbConnect.Advertisements.Remove(item);
                _dbConnect.SaveChanges();
                return Json(new { success = true });

            }
            return Json(new { success = false });
        }
    }
}

BVSneaker/Areas/Admin/Views/Advertisement/Add.cshtml
@model BVSneaker.Models.EF.Advertisement
@{
    ViewBag.Title = "Add advertisement";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Advertisement" class="nav-link">Advertisement</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Add</a>
        </li>
    </ul>
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Add Advertisement</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/Admin/Advertisement">Advertisement</a></li>
                    <li class="breadcrumb-item active">Add</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Advertisement Infomation</h3>

            @*<div class="card-tools">
                    <a href="/menu/add" class="btn btn-primary">Thêm mới</a>
                </div>*@
        </div>
        <div class="card-body">
            <div class="card-body p-0">
                <div class="bs-stepper linear">
                    <div class="bs-stepper-content">
                        @using (Html.BeginForm("Add", "Advertisement", FormMethod.Post, new { }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <!-- your steps content here -->
                            <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Menu Title</label>
                                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Example: New.." })
                                    @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Link</label>
                                    @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Example: New.." })
                                    @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Description</label>
                                    @Html.TextAreaFor(x => x.Description, new { @class = "form-control", style = "height:200px !important;" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Image</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            @Html.TextBoxFor(x => x.Image, new { @id = "txtImage", @class = "form-control" })
                                        </div>
                                        <div class="input-group-append">
                                            <input type="button" value="Choose File" onclick="BrowseServer('txtImage')" />
                                        </div>
                                    </div>
                                </div>
                                <a href="/Admin/Advertisement" class="btn btn-danger">Back</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
    </script>
}

BVSneaker/Areas/Admin/Views/Advertisement/Edit.cshtml
@model BVSneaker.Models.EF.Advertisement
@{
    ViewBag.Title = "Edit menu";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Menu" class="nav-link">Menu</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Edit</a>
        </li>
    </ul>
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Edit menu</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Menu</a></li>
                    <li class="breadcrumb-item active">Edit</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Menu Infomation</h3>

            @*<div class="card-tools">
                    <a href="/menu/add" class="btn btn-primary">Thêm mới</a>
                </div>*@
        </div>
        <div class="card-body">
            <div class="card-body p-0">
                <div class="bs-stepper linear">
                    <div class="bs-stepper-content">
                        @using (Html.BeginForm("Edit", "Advertisement", FormMethod.Post, new { }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(x => x.Adv_Id)
                            <!-- your steps content here -->
                            <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Menu Title</label>
                                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control", @placeholder = "Example: New.." })
                                    @Html.ValidationMessageFor(x => x.Title, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Link</label>
                                    @Html.TextBoxFor(x => x.Alias, new { @class = "form-control", @placeholder = "Example: New.." })
                                    @Html.ValidationMessageFor(x => x.Alias, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Description</label>
                                    @Html.TextAreaFor(x => x.Description, new { @class = "form-control", style = "height:200px !important;" })
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Image</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            @Html.TextBoxFor(x => x.Image, new { @id = "txtImage", @class = "form-control" })
                                        </div>
                                        <div class="input-group-append">
                                            <input type="button" value="Choose File" onclick="BrowseServer('txtImage')" />
                                        </div>
                                    </div>
                                </div>
                                <a href="/Admin/Advertisement" class="btn btn-danger">Back</a>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
    </script>
}

BVSneaker/Areas/Admin/Views/Advertisement/Index.cshtml
@model PagedList.PagedList<BVSneaker.Models.EF.Advertisement>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Advertisement";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Menu" class="nav-link">Menu</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Advertisement" class="nav-link">Advertisement</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Brand" class="nav-link">Brand</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Category" class="nav-link">Categories</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Topic" class="nav-link">Topic</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Order" class="nav-link">Order</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Product" class="nav-link">Product</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Role" class="nav-link">Role</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/Admin/Account" class="nav-link">Account</a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Advertisement Management</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Advertisement</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Advertisement List</h3>

            <div class="card-tools">
                <a href="/Admin/Advertisement/Add" class="btn btn-primary">Add</a>
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    @using (Html.BeginForm("Index", "Advertisement", FormMethod.Get, new { }))
                    {
                        <div class="input-group input-group-sm">
                            @Html.TextBox("Searchtext")
                            <span class="input-group-append">
                                <button type="submit" class="btn btn-info btn-flat"><i class="fas fa-search"></i></button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Number</th>
                        <th>Name</th>
                        <th style="width:300px">Description</th>
                        <th>Created date</th>
                        <th>Modified date</th>
                        <th>Image</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        var i = ((ViewBag.Page - 1) * ViewBag.PageSize) + 1;
                        foreach (var item in Model)
                        {
                            <tr id="trow_@item.Adv_Id">
                                <td>@i</td>
                                <td>@item.Title</td>
                                <td>@item.Description</td>
                                <td>@item.CreateDate.ToString("dd/MM/yyyy")</td>
                                <td>@item.ModDate.ToString("dd/MM/yyyy")</td>
                                <td><img src="@item.Image" style="width:50px" /></td>
                                <td>
                                    <a href="/Admin/Advertisement/Edit/@item.Adv_Id" class="btn btn-sm btn-primary">Edit</a>
                                    <a href="#" data-id="@item.Adv_Id" class="btn btn-sm btn-danger btnDelete">Delete</a>
                                </td>
                            </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="7">There is no record</td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="row">
                <div class="col-6"></div>
                <div class="col-6" style="text-align:right;">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                </div>
            </div>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        $(document).ready(function () {
            $('body').on('click', '.btnDelete', function () {
                var id = $(this).data("id");
                var conf = confirm('Do you want to delete this record?')
                if (conf === true) {
                    $.ajax({
                        url: '/admin/advertisement/delete',
                        type: 'POST',
                        data: { id: id },
                        success: function (rs) {
                            if (rs.success) {
                                $('#trow_' + id).remove(); l
                            }
                        }
                    })
                }
            });
        });
    </script>
}