BVSneaker/Controllers/MenuController.cs
using BVSneaker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BVSneaker.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext _dbConnect = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MenuTop()
        {
            var items = _dbConnect.Menu.OrderBy(x => x.Position).ToList();
            return PartialView("_MenuTop", items);
        }
        public ActionResult AdvertisementSlider()
        {
            var items = _dbConnect.Advertisements.ToList();
            return PartialView("_AdvertisementSlider", items);
        }
        public ActionResult BrandSlider()
        {
            var items = _dbConnect.Brand.ToList();
            return PartialView("_BrandSlider", items);
        }
        public ActionResult MenuCategory()
        {
            var items = _dbConnect.Topic.ToList();
            return PartialView("_MenuTopic", items);
        }
        public ActionResult MenuArrivals()
        {
            var items = _dbConnect.Topic.ToList();
            return PartialView("_MenuArrivals", items);
        }
        public ActionResult MenuLeft(int? id)
        {
            if (id != null)
            {
                ViewBag.TopicId = id;
            }
            var items = _dbConnect.Topic.ToList();
            return PartialView("_MenuLeft", items);
        }
        public ActionResult MenuLeftBrand(int? id)
        {
            if (id != null)
            {
                ViewBag.BrandId = id;
            }
            var items = _dbConnect.Brand.ToList();
            return PartialView("_MenuLeftBrand", items);
        }

        public ActionResult MenuLeftCate(int? id)
        {
            if (id != null)
            {
                ViewBag.CategoryId = id;
            }
            var items = _dbConnect.Category.ToList();
            return PartialView("_MenuLeftCate", items);
        }
    }
}

BVSneaker/Controllers/ProductController.cs
using BVSneaker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using BVSneaker.Models.EF;

namespace BVSneaker.Controllers
{
    public class ProductController : Controller
    {
        private ApplicationDbContext _dbConnect = new ApplicationDbContext();
        // GET: Product
        public ActionResult Index(int? id)
        {
            var items = _dbConnect.Product.Include(s => s.ProductStock).ToList();
            if (id != null)
            {
                items = items.Where(x => x.Topic_Id == id).ToList();
            }
            return View(items);
        }
        public ActionResult IndexBrand(int? id)
        {
            var items = _dbConnect.Product.Include(s => s.ProductStock).ToList();
            if (id != null)
            {
                items = items.Where(x => x.Brand_Id == id).ToList();
            }
            return View(items);
        }
        public ActionResult IndexSearch(string Searchtext)
        {
            var items = _dbConnect.Product.Include(s => s.ProductStock).ToList();
            if (Searchtext != null)
            {
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Name.Contains(Searchtext)).ToList();
            }
            ViewBag.SearchText = Searchtext;
            return View(items);
        }
        public ActionResult ProductTopic(string alias, int? id)
        {
            var items = _dbConnect.Product.Include(s => s.ProductStock).ToList();
            if (id > 0)
            {
                items = items.Where(x => x.Topic_Id == id).ToList();
            }
            var topic = _dbConnect.Topic.Find(id);
            if (topic != null)
            {
                ViewBag.TopicTitle = topic.Title;
            }
            ViewBag.TopicId = id;
            return View(items);
        }
        public ActionResult ProductBrand(string alias, int? id)
        {
            var items = _dbConnect.Product.Include(s => s.ProductStock).ToList();
            if (id > 0)
            {
                items = items.Where(x => x.Brand_Id == id).ToList();
            }
            var brand = _dbConnect.Brand.Find(id);
            if (brand != null)
            {
                ViewBag.BrandTitle = brand.Name;
            }
            ViewBag.BrandId = id;
            return View(items);
        }
        public ActionResult Partial_ItemsByTopicID()
        {
            var items = _dbConnect.Product.Include(s => s.ProductStock).Where(x => x.isHome).Take(15).ToList();
            return PartialView(items);
        }
        public ActionResult Partial_ProductBestSeller()
        {
            var items = _dbConnect.Product.Include(s => s.ProductStock).Where(x => x.isBestSeller).Take(10).ToList();
            return PartialView(items);
        }
        public ActionResult QuickView(int? id)
        {
            var item = _dbConnect.Product
                    .Include(s => s.ProductStock)
                    .SingleOrDefault(p => p.Product_Id == id);
            return PartialView(item);
        }
        public ActionResult Detail(string alias, int? id)
        {
            var item = _dbConnect.Product
                    .Include(s => s.ProductStock)
                    .SingleOrDefault(p => p.Product_Id == id);
            if (item != null)
            {
                _dbConnect.Product.Attach(item);
                item.ViewCount = item.ViewCount + 1;
                _dbConnect.Entry(item).Property(x => x.ViewCount).IsModified = true;
                _dbConnect.SaveChanges();
            }
            return View(item);
        }

    }
}

BVSneaker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>BV Sneaker Shop</title>
    <meta charset="utf-8">s
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/bootstrap4/bootstrap.min.css">
    <link href="~/Content/assets/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/responsive.css">
    <link href="~/Content/assets/styles/contact_styles.css" rel="stylesheet" />
    <link href="~/Content/assets/styles/contact_responsive.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/toastr.css" />
    <script src="~/Content/assets/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/assets/js/"></script>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryval")
</head>

<body>

    <div class="super_container">

        <!-- Header -->

        <header class="header trans_300">

            <!-- Top Navigation -->

            <div class="top_nav">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="top_nav_left">Free shipping on all Viet Nam orders over $50</div>
                        </div>
                        <div class="col-md-6 text-right">
                            <div class="top_nav_right">
                                <ul class="top_nav_menu">

                                    <!-- Currency / Language / My Account -->


                                    <li class="account">
                                        <a href="#">
                                            My Account
                                            <i class="fa fa-angle-down"></i>
                                        </a>
                                        <ul class="account_selection">
                                            @Html.Partial("_LoginPartial")
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main Navigation -->

            <div class="main_nav_container">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-right">
                            <div class="logo_container">
                                <a href="/Home"><img style="width:140px" src="~/Uploads/images/Logo_Trans_2.png" /></a>
                            </div>
                            <nav class="navbar">
                                <ul class="navbar_menu">
                                    @Html.Action("MenuTop", "Menu")
                                </ul>
                                @using (Html.BeginForm("IndexSearch", "Product", FormMethod.Get, new { }))
                                {
                                    <div id="search-box">
                                        @Html.TextBox("Searchtext")
                                        <button type="submit" id="search-btn"><i class="fa fa-search"></i></button>
                                    </div>
                                }
                                <ul class="navbar_user">
                                    @if (User.Identity != null && User.Identity.IsAuthenticated)
                                    {
                                        <li><a href="#"><i class="fa fa-heart" aria-hidden="true"></i></a></li>
                                    }
                                    else
                                    {
                                        <span>&nbsp;</span>
                                    }
                                    <li class="checkout">
                                        <a href="/shopping-cart">
                                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                            <span id="checkout_items" style="background: #f80438;" class="checkout_items">0</span>
                                        </a>
                                    </li>
                                </ul>
                                <div class="hamburger_container">
                                    <i class="fa fa-bars" aria-hidden="true"></i>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

        </header>

        <div class="fs_menu_overlay"></div>
        <div class="hamburger_menu">
            <div class="hamburger_close"><i class="fa fa-times" aria-hidden="true"></i></div>
            <div class="hamburger_menu_content text-right">
                <ul class="menu_top_nav">
                    <li class="menu_item has-children">
                        <a href="#">
                            usd
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="menu_selection">
                            <li><a href="#">cad</a></li>
                            <li><a href="#">aud</a></li>
                            <li><a href="#">eur</a></li>
                            <li><a href="#">gbp</a></li>
                        </ul>
                    </li>
                    <li class="menu_item has-children">
                        <a href="#">
                            English
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="menu_selection">
                            <li><a href="#">French</a></li>
                            <li><a href="#">Italian</a></li>
                            <li><a href="#">German</a></li>
                            <li><a href="#">Spanish</a></li>
                        </ul>
                    </li>
                    <li class="menu_item has-children">
                        <a href="#">
                            My Account
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="menu_selection">
                            <li><a href="#"><i class="fa fa-sign-in" aria-hidden="true"></i>Sign In</a></li>
                            <li><a href="#"><i class="fa fa-user-plus" aria-hidden="true"></i>Register</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        @RenderBody()

        <!-- Footer -->

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
                            <ul class="footer_nav">
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">FAQs</a></li>
                                <li><a href="contact.html">Contact us</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/ckfinder/ckfinder.js"></script>
    <script>
        function searchToggle(obj, evt) {
            var container = $(obj).closest('.search-wrapper');
            if (!container.hasClass('active')) {
                container.addClass('active');
                evt.preventDefault();
            }
            else if (container.hasClass('active') && $(obj).closest('.input-holder').length == 0) {
                container.removeClass('active');
                // clear input
                container.find('.search-input').val('');
            }
        }
    </script>
    <script src="~/Content/assets/js/jsShopping.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    @*<script src="~/Content/assets/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/assets/styles/bootstrap4/popper.js"></script>
    <script src="~/Content/assets/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="~/Content/assets/plugins/Isotope/isotope.pkgd.min.js"></script>
    <script src="~/Content/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
    <script src="~/Content/assets/plugins/easing/easing.js"></script>
    <script src="~/Content/assets/js/custom.js"></script>*@
    @RenderSection("scripts", required: false)
</body>

</html>

BVSneaker/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>BV Sneaker Store</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/bootstrap4/bootstrap.min.css">
    <link href="~/Content/assets/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/plugins/OwlCarousel2-2.2.1/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/responsive.css">
    <link href="~/Content/assets/styles/contact_styles.css" rel="stylesheet" />
    <link href="~/Content/assets/styles/contact_responsive.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/toastr.css" />
    <script src="~/Content/assets/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/assets/js/"></script>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jqueryval")

</head>
<body>
    @RenderBody()
    <!-- /.login-card-body -->
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/clients/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/clients/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>